image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      eval $(gp env -e)
      bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
  - command: |
      make

ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
    - DavidAnson.vscode-markdownlint
    - EditorConfig.editorconfig
    - shd101wyy.markdown-preview-enhanced
    - streetsidesoftware.code-spell-checker
    - yzhang.markdown-all-in-one
