version: '3'

services:
  app:
    build: .
    environment:
      TZ: Asia/Tokyo
    # env_file:
    #   - .env
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - '8000:8000'
    tty: true
