name: GitHub Pages

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}

    steps:
    - uses: actions/checkout@v2
    - name: Format
      id: format
      run: make format
    - name: Update Document
      id: doc
      run: make doc
    - name: Deploy Document
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
